= Things we'll want to ask Grok to do

* Make sure all UI/UX works

** [x] Test manual check enabled/disabled

** [x] Test open post in new tab when isManualCheckEnabled = false

** [x] Test userRequestedManualCheckInNewTab
*** [x] Works on a reply to a deleted post
*** [x] Need to test on a reply to a good post.
***** [x] We also expect that if a post is verified bad, the tab stays open and the post is highlighted in red along with the indicator on the panel changing to red.

*** [x] I had planned to change the logic on identify posts and the way we handle identification links. It might be time to focus on those.

** [x] Test export csv
** [x] Test import csv
** [x] Test reset csv

* [x] Add eyeball link column for potential problem posts in the panel
** [x] Test open post in new tab from panel link

* [x] Are we using the processedPosts list to avoid reprocessing posts? We filter out any that were already tagged with our data element, but we might not be also checking for when a user scrolls back up and re-loads already processed posts. 

* [x] Move eyeballs to left hand column of the panel and make them always visible. Have it replace the yellow dot for potential problem posts.
* [x] Examine the Preact implementation of the panel and see if we can make it more efficient. 
* [ ] Save user changed theme and stop defaulting unless theme had never been set before.
* [ ] Stop using mutation observer or find a way to do a custom check. Look for changes in post qty first (using highlightPosts selector) and then changes in the innerHTML of any post second. Poling might work better for that. We could hand the first query results to highlightPosts if we detect changes that need processing in order to save a second selection.
* [ ] Fix resize panel
* [ ] Fix move panel

* [ ] Make sure we can open with the eyeballs from the panel if manual check is disabled
* [ ] Make sure we can open the old way with the eyeballs if manual check is disabled and panel didn't open.
* [ ] Does mutation observer fire while we're highlighting posts?
* [ ] Pause mutation observer while highlight posts is running?

* Clarify dom for post container and X.com behavior

* Get collapsing feature working as a feature of highlightPosts
** We can use a class to collapse when that is enabled.

* Add unit tests to increase coverage of all but UI/UX stuff.

*MERGE*: collapsing into main

* Switch from HTM to JSX for Preact
* Swtich to TypeScript
* Push list of bad communities and system notice strings into editable data with a default starting set of data.