= Things we'll want to ask Grok to do

* Make sure all UI/UX works

** Test manual check enabled/disabled
*** Clicking the button when it shows ":On" logs that it toggled off and evidence proves this is correct, but the button doesn't change and still shows ":On". 
*** If I refresh the page, the button shows the new state:Off.

** Test open post in new tab
*** This works when isManualCheckEnabled = false

** Test userRequestedManualCheckInNewTab
*** Works on a reply to a deleted post
*** Need to test on a reply to a good post.
*** While trying this on ApostleJohnW page, I have a yellow post show up after scrolling for a while but it doesn't show up in the panel list and when I click the eyeballs, a new tab opens but nothing loads. Back on the main page, I get an alert open with a message about possible rate limiting because of no posts being found after a given timeout.
*** I had planned to change the logic on identify posts and the way we handle identification links. It might be time to focus on those.

** Test export csv
** Test import csv
** Test reset csv



* rename isRateLimited to isRateLimitedDetected

* Add eyeball link column for potential problem posts in the panel
** Test open post in new tab from panel link

* Make sure we can open the old way with the eyeballs if manual check is disabled

* Clarify dom for post container and X.com behavior

[cols="1,1,2,2",options="header"]
|===
| Variable            | Type       | Purpose                                      | Key Usage Contexts
| `processedPosts`    | `Map`      | Stores analysis and status of all posts      | Highlighting, Manual Check, Export
| `problemLinks`      | `Set`      | Tracks hrefs of collapsed problematic posts  | `collapseArticlesWithDelay`, Reset
| `fullyProcessedPosts`| `Set`     | Marks posts fully processed for collapsing   | `collapseArticlesWithDelay`, Reset
| `postContainer`     | DOM/`null` | References the posts’ DOM container          | Highlighting, Page Navigation
|===

We can get rid of all but processedPosts which can include good posts but have them filtered out of the panel display list by default.
* We can get rid of collapseArticlesWithDelay along with problemLinks and fullyProcessedPosts

* Get collapsing feature working as a feature of highlightPosts
** We can use a class to collapse when that is enabled.

*MERGE*: collapsing into main

* Switch from HTM to JSX for Preact
* Swtich to TypeScript
* Push list of bad communities and system notice strings into editable data with a default starting set of data.